# Generated by Django 6.0.5 on 2026-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_icebreaker',
            field=models.BooleanField(default=False, verbose_name='Buzkıran (Önemli)'),
        ),
    ]
