# Generated by Django 6.0.5 on 2026-05-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_is_icebreaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Duygu Adı')),
            ],
            options={
                'verbose_name': 'Duygu',
                'verbose_name_plural': 'Duygular',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.emotion', verbose_name='Duygu'),
        ),
    ]
