# Generated by Django 6.0.5 on 2026-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emotion_entry_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Dönüm Noktası (Örn: İlk Tanışma)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Özel Not')),
                ('date', models.DateField(verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Dönüm Noktası',
                'verbose_name_plural': 'Dönüm Noktaları',
                'ordering': ['-date'],
            },
        ),
    ]
